mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path
from . import views

#namespace
app_name = 'polls'

#url list
urlpatterns = [
    #path('',views.index, name = 'index'),
    #path('details/<int:question_id>',views.detail,name = 'detail'),
    #path('details/<int:question_id>/result/', views.results,name = 'results'),
    #path('details/<int:question_id>/vote/', views.vote, name = 'vote'),
    path('', views.IndexView.as_view(), name='index'),
    path('details/<int:pk>', views.DetailView.as_view(), name='details'),
    path('details/<int:pk>/results', views.ResultsView.as_view(), name= 'results'),
    path('details/<int:question_id>/vote/', views.vote, name = 'vote'),
    path('testupload/', views.testUpload, name = 'testUpload'),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime
import pytz
#convert datetime to specific timezone
zone = pytz.UTC
# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    # def was_published_recently(self):
    #     return (self.pub_date.to_python().month == timezone.datetime.now().month) \
    #            and  \
    #            (self.pub_date.to_python().day >= timezone.datetime.now().day-1) \
    #            and \
    #            (self.pub_date.to_python().year == timezone.now().year)

    def was_published_recently(self):
        # return self.pub_date >= zone.localize(timezone.datetime.now() - datetime.timedelta(days=1))
        now = timezone.now()
        return now - datetime.timedelta(days=1)<=self.pub_date<=now

    """modify how was_published_recently row is displayed in admin site"""
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published Recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404,HttpResponseRedirect
from django.template import loader
from django.utils import timezone
from django.views import generic
from django.urls import reverse
from .models import Question,Choice
from django.core.files.storage import FileSystemStorage

# Create your views here.


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # template = loader.get_template('polls/index.html')
    # context = {
    #     'latest_question_list':latest_question_list,
    # }
    # return HttpResponse(template.render(context, request))
    # context = {
    #     'latest_question_list':latest_question_list,
    # }
    # return render(request,'polls/index.html',context)

# def detail(request, question_id):
#     question =get_object_or_404(Question,pk=question_id)
#     return render(request, 'polls/details.html', {'question':question})
#
# def results(request,question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request,'polls/results.html',
#                   {'question':question,})

def vote(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError,Choice.DoesNotExist):
        return render(request,'polls/details.html',
                      {
                          'question':question,
                          'error_message': "No choice selected",
                      })
    else:
        selected_choice.votes +=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results',args=(question_id,)))

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    def get_queryset(self):
        """return last 05 published questions"""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/details.html'
    def get_queryset(self):
        """filter questions that have yet to be published"""
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def testUpload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        # file upload tu giao dien (input id = myfile)
        myfile = request.FILES['myfile']
        # thao tac voi file (demo: save file to system)
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        # render giao dien tra ve 
        return render(request, 'polls/simple_upload.html', {
            'uploaded_file_url': uploaded_file_url
        })
    return render(request, 'polls/simple_upload.html')

polls/templates/polls/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %} default title {% endblock %}</title>
  </head>
  <body>
    <div id = 'container-fluid'>
        {% block content %}
        default content
        {% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

polls/templates/polls/details.html
{% extends 'polls/base.html' %}
{% block title %} Question Detail {% endblock %}
{% block content %}
<a href="{% url 'polls:index' %}">back to index</a>
<h1>{{question}}</h1>

{% if error_message %}
<p>
    <strong>
        {{error_message}}
    </strong>
</p>
{% endif %}


<form action = "{% url 'polls:vote' question.id %}" method = 'post'>
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input
            type="radio"
            name = 'choice'
            id = 'choice{{ forloop.counter}}'
            value="{{choice.id}}"
    >
    <label for="choice{{ forloop.counter}}}}">
        {{choice.choice_text}}
    </label>
    <br>
    {% endfor %}
    <input class = 'btn btn-primary'
            type = 'submit'
            value = 'Vote'
    >
</form>

{% endblock %}

polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% block title %} Question List {% endblock %}
<!--{% load static %}-->
<!--<link rel="stylesheet" href="{% static 'polls/style.css' %}">-->
{% block content %}
{% if latest_question_list %}
    <table class = 'table'>
        <tr>
            <th>Question</th>
            <th>Published Date</th>
        </tr>
        <tbody>
    {% for question in latest_question_list %}
        <tr>
        <th><a href="{% url 'polls:details' question.id %}">{{ question.question_text }}</a></th>
        <td>{{question.pub_date}}</td>
        </tr>
    {% endfor %}

        </tbody>
    </table>

{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

polls/templates/polls/results.html
<h1>{{question}}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>
        {{choice}} -- {{choice.votes}} vote{{choice.votes|pluralize}}
    </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:details' question.id %}">Vote again?</a>

polls/templates/polls/simple_upload.html
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>

  {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}

  <p><a href="{% url 'home' %}">Return to home</a></p>
{% endblock %}

polls/templates/polls/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>test template</h1>
</body>
</html>